project_id = "rqngbtkdjrgoevnmgfys"

[functions.compare-products]
verify_jwt = false

[functions.get-installment-rates]
verify_jwt = false

[functions.portal-login]
verify_jwt = false

[functions.portal-get-receivables]
verify_jwt = false